import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/theme-toggle";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased container`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header className="sticky top-0 z-50  bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60 mb-6">
            <div className="container">
              <div className="flex items-center justify-between  py-4 border-b">
                <nav>
                  <ul>
                    <li>
                      <Link href={"/"}>Inicio</Link>
                    </li>
                  </ul>
                </nav>
                <ModeToggle />
              </div>
            </div>
          </header>
          <main className="container">{children}</main>

          <footer className="container py-6">
            <div className="mb-6 border-t"></div>
            <p className="text-center text-sm text-muted-foreground">
              Powered by{" "}
              <a
                href="https://www.linkedin.com/in/estherpaz/"
                target="_blank"
                rel="noopener noreferrer"
                className="text-foreground hover:underline"
              >
                Esther Paz
              </a>
            </p>
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
